# Configuración del hook con AdvancedClans
advancedclans:
  enabled: true
  prevent-clan-damage: true
  prevent-ally-damage: true

messages:
  prefix: ""
  reload: "&aLa configuración ha sido recargada"
  no-permission: "&cNo tienes permiso para usar este comando"
  enchant-applied: "&aEncantamiento %enchant% %level% aplicado con éxito"
  enchant-already-applied: "&cEste item ya tiene el encantamiento %enchant%"
  no-item: "&cDebes tener un item en la mano"
  no-valid-enchant: "&cEncantamiento no válido"
  book-given: "&aHas recibido un libro de encantamiento %enchant% %level%"
  book-inventory-full: "&cTu inventario está lleno"
  book-applied: "&aHas aplicado el encantamiento %enchant% %level% al item"
  book-invalid-item: "&cNo puedes aplicar este encantamiento a este item"
  pumpkin-placed: "&8[&6&lHALLOWEENFY&8] &fHas colocado una calabaza en la cabeza de &6%player%"
  pumpkin-received: "&8[&6&lHALLOWEENFY&8] &c¡%player% te ha colocado una calabaza en la cabeza!"
  helmet-inventory: "&8[&6&lHALLOWEENFY&8] &fTu casco ha sido movido a tu inventario"
  helmet-dropped: "&8[&6&lHALLOWEENFY&8] &fTu casco ha sido tirado al suelo"
  poison-applied: "&8[&e&lH&6&lC&e&lN&8] &fHas envenenado a &6%player% &fpor &e%duration% &fsegundos"
  poison-received: "&8[&e&lH&6&lC&e&lN&8] &c¡&c%player% te ha envenenado por %duration% segundos!"
  slowness-applied: "&8[&e&lH&6&lC&e&lN&8] &fHas ralentizado a &6%player% &fpor &e%duration% &fsegundos"
  slowness-received: "&8[&e&lH&6&lC&e&lN&8] &c¡%player% te ha ralentizado por %duration% segundos!"
  ice-applied: "&8[&b&lI&f&lC&b&lE&8] &fHas encapsulado a &6%player% &fen hielo por &b%duration% &fsegundos"
  ice-received: "&8[&b&lI&f&lC&b&lE&8] &c¡%player% te ha encapsulado en hielo por %duration% segundos!"
  # Mensajes para libros de encantamientos
  book-title: "&b%enchant% %level%"
  book-enchant-info: "&7Encantamiento: &b%enchant%"
  book-level-info: "&7Nivel: &b%level%"
  book-instructions-1: "&eArrastra este libro sobre un item"
  book-instructions-2: "&epara aplicar el encantamiento"

enchants:
  soulbound:
    name: "SoulBound"
    enabled: true
    max-level: 2
    restricted-items:
      - 322
      - "322:1"
      - POTION
    levels:
      1:
        chance: 50
        lore:
          - "&7SoulBound I"
        description: ""
      2:
        chance: 100
        lore:
          - "&c&lSoulBound II"
        description: ""

  halloweenefy:
    name: "Halloweenefy"
    enabled: true
    max-level: 3
    allowed-items:
      - WOOD_SWORD
      - STONE_SWORD
      - IRON_SWORD
      - GOLD_SWORD
      - DIAMOND_SWORD
      - WOOD_AXE
      - STONE_AXE
      - IRON_AXE
      - GOLD_AXE
      - DIAMOND_AXE
    levels:
      1:
        chance: 1
        lore:
          - ""
        description: "&6&lH&e&la&6&ll&e&ll&6&lo&e&lw&6&le&e&le&6&ln&6&lf&e&ly &6&lI"
      2:
        chance: 1
        lore:
          - ""
        description: "&6&lH&e&la&6&ll&e&ll&6&lo&e&lw&6&le&e&le&6&ln&6&lf&e&ly &6&lI&e&lI"
      3:
        chance: 3
        lore:
          - "&6&lH&e&la&6&ll&e&ll&6&lo&e&lw&6&le&e&le&6&ln&6&lf&e&ly &6&lI&e&lI&6&lI"
        description: ""

  poison:
    name: "Poison"
    enabled: true
    max-level: 3
    allowed-items:
      - WOOD_SWORD
      - STONE_SWORD
      - IRON_SWORD
      - GOLD_SWORD
      - DIAMOND_SWORD
    levels:
      1:
        chance: 8
        lore:
          - "&2&lP&a&lo&2&li&a&ls&2&lo&a&ln &2&lI"
        description: ""
        duration: 8
        amplifier: 0
      2:
        chance: 6
        lore:
          - "&2&lP&a&lo&2&li&a&ls&2&lo&a&ln &2&lI&a&lI"
        description: ""
        duration: 6
        amplifier: 1
      3:
        chance: 3
        lore:
          - "&2&lP&a&lo&2&li&a&ls&2&lo&a&ln &2&lI&a&lI&2&lI"
        description: ""
        duration: 4
        amplifier: 2

  iceaspect:
    name: "Ice Aspect"
    enabled: true
    max-level: 3
    # Configuración del cubo de hielo
    cube:
      size: 6
      hollow: true
      replace-air-only: true
    allowed-items:
      - WOOD_SWORD
      - STONE_SWORD
      - IRON_SWORD
      - GOLD_SWORD
      - DIAMOND_SWORD
      - WOOD_AXE
      - STONE_AXE
      - IRON_AXE
      - GOLD_AXE
      - DIAMOND_AXE
    levels:
      1:
        chance: 8
        lore:
          - "&b&lI&f&lc&b&le &b&lI"
        description: ""
        duration: 5
      2:
        chance: 6
        lore:
          - "&b&lI&f&lc&b&le &b&lI&f&lI"
        description: ""
        duration: 5
      3:
        chance: 4
        lore:
          - "&b&lI&f&lc&b&le &b&lI&f&lI&b&lI"
        description: ""
        duration: 5

  slowness:
    name: "Slowness"
    enabled: true
    max-level: 3
    allowed-items:
      - WOOD_SWORD
      - STONE_SWORD
      - IRON_SWORD
      - GOLD_SWORD
      - DIAMOND_SWORD
      - WOOD_AXE
      - STONE_AXE
      - IRON_AXE
      - GOLD_AXE
      - DIAMOND_AXE
    levels:
      1:
        chance: 8
        lore:
          - "&7&lS&f&ll&f&lo&7&lw &7&lI"
        description: ""
        duration: 8
        amplifier: 0
      2:
        chance: 6
        lore:
          - "&7&lS&f&ll&f&lo&7&lw &7&lI&f&lI"
        description: ""
        duration: 6
        amplifier: 1
      3:
        chance: 3
        lore:
          - "&7&lS&f&ll&f&lo&7&lw &7&lI&f&lI&7&lI"
        description: ""
        duration: 4
        amplifier: 2