messages:
  prefix: "&8[&bEnchantsHCN&8]"
  reload: "&aLa configuración ha sido recargada"
  no-permission: "&cNo tienes permiso para usar este comando"
  enchant-applied: "&aEncantamiento %enchant% %level% aplicado con éxito"
  no-item: "&cDebes tener un item en la mano"
  no-valid-enchant: "&cEncantamiento no válido"
  book-given: "&aHas recibido un libro de encantamiento %enchant% %level%"
  book-inventory-full: "&cTu inventario está lleno"
  book-applied: "&aHas aplicado el encantamiento %enchant% %level% al item"
  book-invalid-item: "&cNo puedes aplicar este encantamiento a este item"
  pumpkin-placed: "&aHas colocado una calabaza en la cabeza de %player%"
  pumpkin-received: "&c¡%player% te ha colocado una calabaza en la cabeza!"
  helmet-inventory: "&aTu casco ha sido movido a tu inventario"
  helmet-dropped: "&aTu casco ha sido tirado al suelo"
  poison-applied: "&aHas envenenado a %player% por %duration% segundos"
  poison-received: "&c¡%player% te ha envenenado por %duration% segundos!"
  slowness-applied: "&aHas ralentizado a %player% por %duration% segundos"
  slowness-received: "&c¡%player% te ha ralentizado por %duration% segundos!"
  # Mensajes para libros de encantamientos
  book-title: "&b%enchant% %level%"
  book-enchant-info: "&7Encantamiento: &b%enchant%"
  book-level-info: "&7Nivel: &b%level%"
  book-instructions-1: "&eArrastra este libro sobre un item"
  book-instructions-2: "&epara aplicar el encantamiento"

enchants:
  soulbound:
    name: "SoulBound"
    enabled: true
    max-level: 2
    restricted-items:
      - 322
      - "322:1"
      - POTION
    levels:
      1:
        chance: 50
        lore:
          - "&7SoulBound I"
          - ""
        description: ""
      2:
        chance: 100
        lore:
          - "&7SoulBound II"
          - "&7Mantiene tus items al morir"
        description: ""

  halloweenefy:
    name: "Halloweenefy"
    enabled: true
    max-level: 3
    allowed-items:
      - WOOD_SWORD
      - STONE_SWORD
      - IRON_SWORD
      - GOLD_SWORD
      - DIAMOND_SWORD
      - WOOD_AXE
      - STONE_AXE
      - IRON_AXE
      - GOLD_AXE
      - DIAMOND_AXE
    levels:
      1:
        chance: 1
        lore:
          - "&6Halloweenefy I"
          - ""
        description: ""
      2:
        chance: 1
        lore:
          - "&6Halloweenefy II"
          - ""
          - "&7Coloca calabazas en las cabezas"
        description: ""
      3:
        chance: 3
        lore:
          - ""
          - "&6&lH&e&la&6&ll&e&ll&6&lo&e&lw&6&le&e&le&6&ln&6&lf&e&ly &6&lI&e&lI&6&lI"
          - ""
        description: ""

  poison:
    name: "Poison"
    enabled: true
    max-level: 3
    allowed-items:
      - WOOD_SWORD
      - STONE_SWORD
      - IRON_SWORD
      - GOLD_SWORD
      - DIAMOND_SWORD
    levels:
      1:
        chance: 5
        lore:
          - "&2Poison I"
          - ""
        description: "&7Tiene un &f5%&7 de probabilidad de envenenar al enemigo"
        duration: 5
        amplifier: 0
      2:
        chance: 10
        lore:
          - "&2Poison II"
          - ""
          - "&7Envenena a tus enemigos"
        description: "&7Tiene un &f10%&7 de probabilidad de envenenar al enemigo"
        duration: 7
        amplifier: 0
      3:
        chance: 15
        lore:
          - "&2Poison III"
          - ""
          - "&7Envenena a tus enemigos"
          - "&7con mayor potencia"
        description: "&7Tiene un &f15%&7 de probabilidad de envenenar al enemigo"
        duration: 10
        amplifier: 1

  slowness:
    name: "Slowness"
    enabled: true
    max-level: 3
    allowed-items:
      - WOOD_SWORD
      - STONE_SWORD
      - IRON_SWORD
      - GOLD_SWORD
      - DIAMOND_SWORD
      - WOOD_AXE
      - STONE_AXE
      - IRON_AXE
      - GOLD_AXE
      - DIAMOND_AXE
    levels:
      1:
        chance: 5
        lore:
          - "&8Slowness I"
          - ""
        description: "&7Tiene un &f5%&7 de probabilidad de ralentizar al enemigo"
        duration: 4
        amplifier: 0
      2:
        chance: 10
        lore:
          - "&8Slowness II"
          - ""
          - "&7Ralentiza a tus enemigos"
        description: "&7Tiene un &f10%&7 de probabilidad de ralentizar al enemigo"
        duration: 6
        amplifier: 1
      3:
        chance: 15
        lore:
          - "&8Slowness III"
          - ""
          - "&7Ralentiza a tus enemigos"
          - "&7con mayor potencia"
        description: "&7Tiene un &f15%&7 de probabilidad de ralentizar al enemigo"
        duration: 8
        amplifier: 2