name: EnchantsHCN
version: 1.0.6
main: com.wish.EnchantsHCN
author: wwishhdev
description: Plugin de encantamientos personalizados
softdepend: [AdvancedClans]
commands:
  enchantshcn:
    description: Comando principal del plugin
    usage: /<command> <enchant> [nivel]
    aliases: [ehcn]
  enchantshcnreload:
    description: Recarga la configuración del plugin
    usage: /<command>
    aliases: [ehcnreload]
  enchantshcnbook:
    description: Da un libro encantado al jugador
    usage: /<command> <enchant> [nivel] [jugador]
    aliases: [ehcnbook]